---
- name: Tomcat deployment playbook
  hosts: default
  become: true
  become_method: sudo

  roles:
    - role: 'roles/tomcat'
    - role: 'roles/certbot'
    - role: 'roles/swap'
  
  tasks:
    - name: set timezone to America/Fortaleza
      timezone:
        name: America/Fortaleza
